name: ency

services:
- name: nest-api
  github:
    repo: milan090/ency
    branch: develop
    deploy_on_push: true
  source_dir: ency-backend
  run_command: yarn start:prod
  routes:
  - path: /api