version: "3.9"

services:
  nest-api:
    container_name: nest-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - PORT=3000
    ports:
      - 3000:3000
    env_file:
      - .env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/


volumes:
  postgres:
    name: nest-db
