version: "3.9"

services:
  nest-api:
    container_name: nest-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    ports:
      - 8080:8080
    env_file:
      - .env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/


volumes:
  postgres:
    name: nest-db
